### ISSUE TITLE
Vertaisarviointi #1

### ISSUE THREAD

**Issue by Uxusino** [phuvio/restaurant-finder#1]
**1. Repositorion rakenne ja dokumentaatio**

Tykkäsin paljon siitä, miten projektin github-sivua ylläpidetään. Sovelluksen idea on esitetty tosi monipuolisesti myös hyödyntäen kuvia, mikä on tosi kivaa. Itsestään idea on mielenkiintoinen.
Commitit ovat todella yskityiskohtaisia, minkä takia on helppoa seurata kehityksen etenemistä.

**2. Sovellus käytännössä**

Sovellus on tuotu Fly.io:on, mistä kiitän, sillä toisen projektin asentaminen omalle koneelle voi olla haastava juttu. Toisaalta kohtasin jotain ongelmia käytäessäni sovellusta:
- Rekisteröityessäni kohtasin virheen "Rekisteröinti ei onnistunut". Oivalsin, että se johtuu siitä, että salasana oli liian lyhyt. Mielestäni olisi hyvää tehdä erillinen virheilmoitus siitä, mitä meni vikaan, koska käyttäjä ei tiedä, oliko vika hänen syötteessään tai oliko se jokin palvelimen vika.
- Rekisteröitymisen jälkeen en enää päässyt profiiliin enkä pääsivulle ja selain näytti "Internal Server Error". Jotta pääsisin eroon virheestä, poistin omaa dataa, jotta voisin kirjautua ulos.
- Ilman sisäänkirjautumista arvostelun lisääminen myös tuo "Internal Server Error"

Kun kokeilin luoda uusi tunnus, en kohdannut virhettä ja kaikki on toiminut kuten pitäisi. Haku onnistuu erinomaisesti ja hae myös kuvauksen mukaan, esim. jos kirjoittaa "vegaani" niin se näyttää sopivan ravintolan.

Kirjauduin ulos ja yritin kirjautua sisään uudelleen, mutta taas tuli virhe "Internal Server Error". Aina kun yritin kirjautua sisään niin se on toiminut 50/50. Ehkä se voisi johtua Fly.io:n omista ongelmista?

**3. Koodi ja tietokannan rakenne**

Koodi on selkeä ja kaikki funktiot asianmukaisia. Tietokannassa on kaikki tarvittavat taulut ja rakenne on sopiva. 

Vaikka ulkoasua ei ole vielä suunniteltu, sivusto näyttää siistiltä ja selkeältä ja siellä on helppoa navigoida. En tiedä, johtuivatko kohtaamani virheet bugeista tai Fly.io:n palvelimesta, mutta sitä huolimatta tosi hyvää työtä! :)

**Comment by phuvio** [comment]
Kiitos hyvästä palautteesta. 
Sovellus päivitetty:
- käyttäjän kirjautuminen korjattu
- csrf-tokenin käyttöönotto 
- käyttäjähallinnan käyttöönotto
- virheilmoitusten parantaminen
- bugien korjaus
- layoutin viimeistely
